name: ci
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: shivammathur/setup-php@v2
      - run: cd VMTask && composer install
      - run: cd VMTask && vendor/bin/phpunit